-- 코드를 입력하세요
SELECT res.CAR_ID as CAR_ID, res.AVERAGE_DURATION as AVERAGE_DURATION
FROM (SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) as AVERAGE_DURATION 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      GROUP BY CAR_ID 
      ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC) as res
WHERE res.AVERAGE_DURATION >= 7;